### ISSUE TITLE
Multiple instances... 

### ISSUE THREAD

**Issue by Snille** [CatoAntonsen/MMM-MotionEye#1]
Hi!
Here is a feature request. :)
I'm using your module to overview 3 different cameras and I have activated the "hide when no motion" function. The problem is that all the video-streams gets shown / hidden when only one have motion / no motion. 
There needs to be a way to tell what instans that has motion.
There needs to be an ID of some kind both in the config.js and in the "web hook link".

Thank you for a great module otherwise. 

Best regards Snille

**Comment by CatoAntonsen** [comment]
Check out version 1.2.0. Let me know if I can close this issue or not :-)

**Comment by Snille** [comment]
Yes! Working great! 
Thank you very much!
