### ISSUE TITLE
Close stream when module is hidden.

### ISSUE THREAD

**Issue by Snille** [CatoAntonsen/MMM-MotionEye#2]
Hi again!
Because I'm using now 6 camera streams to my mirror (showing only when there is movements) there are lot's of bandwidth being wasted when the module is hidden. Would there be possible to "stop" the stream when the module gets hidden?

Thank you! :)

**Comment by Snille** [comment]
I believe this is fixed. :)

**Comment by michael24h** [comment]
hi 
how to stop module
