### ISSUE TITLE
Show animation not fading...

### ISSUE THREAD

**Issue by Snille** [CatoAntonsen/MMM-MotionEye#8]
Hi again,
I just realized that the "show"-animation is not working. When something triggers the camera, the show of the module is instant not "animated". It's a bit strange though, you do have the 2000ms delay on the "show" line in the code. So I cant understand why it happens like that... :)

**Comment by CatoAntonsen** [comment]
I suspect it's either a bug or not possible to change opacity on images in Electron. I just had the same issue on a new module I'm making that uses HTML canvas. It looked beautiful in Chrome on my dev-machine, but butt ugly on the mirror...

**Comment by Snille** [comment]
Hmm, nah got to be something else, I'm testing on my "develop"-mirror. And that one I view in Chrome... Besides the "hide" works both on the mirror (electron) and in Chrome... Basically it's doing the exact same thing but in "reverse"... Bug in the Mirror software you think?

**Comment by CatoAntonsen** [comment]
Not sure, I'll keep this case open until I have some time. Should be easy to make a dummy module with an image and test changing opacity on it...

**Comment by CatoAntonsen** [comment]
Hi, I found the bug in MM and pushed a PR: https://github.com/MichMich/MagicMirror/pull/744
