### ISSUE TITLE
Love this module!!

### ISSUE THREAD

**Issue by asifma** [CatoAntonsen/MMM-MotionEye#9]
Not on issue. Just dont know how to give good feedback? 
Anyway!! So nice!! Great job 👍 

Keep up the good work :)

**Comment by CatoAntonsen** [comment]
Hi, glad you like it! I've created a topic on the Magic Mirror forum for this module: https://forum.magicmirror.builders/topic/1085/mmm-motioneye-surveillance-video-stream-on-your-mirror
